#!/usr/bin/env python3
"""Convert a2x/cs2-dumper JSON output into config/offsets.cfg.

Usage:
    1. Dump the current game build (https://github.com/a2x/cs2-dumper):
         cs2-dumper.exe            # writes output/offsets.json, output/client_dll.json
    2. Convert:
         python3 cs2dumper_to_cfg.py output/offsets.json output/client_dll.json \\
             -o ../config/offsets.cfg

The dumper's JSON layout has shifted across releases; this script handles the
two common shapes ({"client.dll": {...}} and flat) and prints anything it
could not map so you can fill it in by hand.
"""

import argparse
import json
import sys

# offsets.cfg key -> (json source, dumper name)
GLOBALS = {
    "client.dwEntityList": "dwEntityList",
    "client.dwLocalPlayerController": "dwLocalPlayerController",
    "client.dwLocalPlayerPawn": "dwLocalPlayerPawn",
}

SCHEMA = {
    "schema.CBasePlayerController.m_hPawn": ("CBasePlayerController", "m_hPawn"),
    "schema.CBasePlayerController.m_steamID": ("CBasePlayerController", "m_steamID"),
    "schema.C_CSPlayerPawnBase.m_pWeaponServices": ("C_CSPlayerPawnBase", "m_pWeaponServices"),
    "schema.C_CSPlayerPawn.m_EconGloves": ("C_CSPlayerPawn", "m_EconGloves"),
    "schema.CPlayer_WeaponServices.m_hMyWeapons": ("CPlayer_WeaponServices", "m_hMyWeapons"),
    "schema.CPlayer_WeaponServices.m_hActiveWeapon": ("CPlayer_WeaponServices", "m_hActiveWeapon"),
    "schema.C_EconEntity.m_AttributeManager": ("C_EconEntity", "m_AttributeManager"),
    "schema.C_AttributeContainer.m_Item": ("C_AttributeContainer", "m_Item"),
    "schema.C_EconItemView.m_iItemDefinitionIndex": ("C_EconItemView", "m_iItemDefinitionIndex"),
    "schema.C_EconItemView.m_iEntityQuality": ("C_EconItemView", "m_iEntityQuality"),
    "schema.C_EconItemView.m_iItemID": ("C_EconItemView", "m_iItemID"),
    "schema.C_EconItemView.m_iAccountID": ("C_EconItemView", "m_iAccountID"),
    "schema.C_EconItemView.m_bInitialized": ("C_EconItemView", "m_bInitialized"),
    "schema.C_EconItemView.m_AttributeList": ("C_EconItemView", "m_AttributeList"),
    "schema.CAttributeList.m_Attributes": ("CAttributeList", "m_Attributes"),
    "schema.CEconItemAttribute.m_iAttributeDefinitionIndex": (
        "CEconItemAttribute",
        "m_iAttributeDefinitionIndex",
    ),
    "schema.CEconItemAttribute.m_nValue": ("CEconItemAttribute", "m_nValue"),
    "schema.CEconItemAttribute.m_flValue": ("CEconItemAttribute", "m_flValue"),
}


def unwrap(data, module):
    """Accept both {"client.dll": {...}} and flat {...} dumper output."""
    if isinstance(data, dict) and module in data and isinstance(data[module], dict):
        return data[module]
    return data


def find_field(classes, cls, field):
    node = classes.get(cls)
    if not isinstance(node, dict):
        return None
    fields = node.get("fields", node)
    value = fields.get(field)
    return value if isinstance(value, int) else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("offsets_json")
    ap.add_argument("client_dll_json")
    ap.add_argument("-o", "--out", default="offsets.cfg")
    args = ap.parse_args()

    with open(args.offsets_json) as f:
        offsets = unwrap(json.load(f), "client.dll")
    with open(args.client_dll_json) as f:
        client = unwrap(json.load(f), "client.dll")

    classes = client.get("classes", client)

    lines = [
        "# offsets.cfg - generated by cs2dumper_to_cfg.py",
        "# Verify layout.* keys against the current build before use.",
        "",
    ]
    missing = []

    for key, name in GLOBALS.items():
        value = offsets.get(name)
        if isinstance(value, int):
            lines.append(f"{key} = {hex(value)}")
        else:
            missing.append(key)
            lines.append(f"{key} = 0x0  # TODO: not found in offsets.json ({name})")

    lines.append("")
    for key, (cls, field) in SCHEMA.items():
        value = find_field(classes, cls, field)
        if value is not None:
            lines.append(f"{key} = {hex(value)}")
        else:
            missing.append(key)
            lines.append(f"{key} = 0x0  # TODO: not found ({cls}.{field})")

    lines += [
        "",
        "# layout defaults - confirm against the current build",
        "layout.attr.stride = 0x18",
        "layout.utlvector.count_rel = 0x0",
        "layout.utlvector.data_rel = 0x8",
        "layout.entity.chunk_base = 0x10",
        "layout.entity.chunk_shift = 9",
        "layout.entity.index_mask = 0x1FF",
        "layout.entity.identity_stride = 0x78",
        "",
    ]

    with open(args.out, "w") as f:
        f.write("\n".join(lines))

    print(f"[+] wrote {args.out}")
    if missing:
        print(f"[!] {len(missing)} key(s) need manual attention:")
        for key in missing:
            print(f"    - {key}")
        sys.exit(2)


if __name__ == "__main__":
    main()
